export { default as DefaultLayout} from './defaultLayout/DefaultLayout'
export { default as EmployeeLayout} from './pagelayout/employeeLayout/EmployeeLayout'
export { default as Notification} from './pagelayout/notificationlayout/Notification'
export { default as PayRollLayout} from './pagelayout/payrollLayout/PayRollLayout'
export { default as MangerLayout} from './management/MangerLayout'